variables:
    TERRAFORM_PLAN_FILE: tfplan

stages:
    - plan
    - apply

.images:
    terraform: &image_terraform
        image:
            name: hashicorp/terraform:1.6.6
            entrypoint: [""]

.assume role:
    assume_role_token: &assume_role_token
        id_tokens:
            GITLAB_OIDC_TOKEN:
                  aud: https://gitlab.revolve.team
    script: &assume_role_script
        - apk add --no-cache aws-cli
        - >
            export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
            $(aws sts assume-role-with-web-identity
            --role-arn ${ROLE_ARN}
            --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
            --web-identity-token ${GITLAB_OIDC_TOKEN}
            --duration-seconds 3600
            --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
            --output text))
        - aws sts get-caller-identity

.cache-terraform: &cache_terraform
    cache:
        key: ${CI_PIPELINE_ID}-terraform-${CI_COMMIT_REF_SLUG}
        paths:
            - .terraform/
            - .terraform.lock.hcl

.cache-terraform-pull: &cache_terraform_pull
    extends:
        - .cache-terraform
    cache:
        policy: pull-push


terraform_plan:
    <<: *image_terraform
    <<: *cache_terraform_pull
    <<: *assume_role_token
    stage: plan
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'
        - if: '$CI_COMMIT_BRANCH == "main"'
    script:
        - *assume_role_script
        - terraform init
        - terraform plan -out=${TERRAFORM_PLAN_FILE}
    artifacts:
        paths:
            - $TERRAFORM_PLAN_FILE

terraform_apply:
    <<: *image_terraform
    <<: *cache_terraform_pull
    <<: *assume_role_token
    stage: apply
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'
        - if: '$CI_COMMIT_BRANCH == "main"'
        - when: manual
    script:
        - *assume_role_script
        - terraform apply ${TERRAFORM_PLAN_FILE}
    artifacts:
        paths:
            - $TERRAFORM_PLAN_FILE




