variables:
    TERRAFORM_PLAN_FILE: tfplan

stages:
    - plan
    - apply

.images:
    terraform: &image_terraform
        image:
            name: hashicorp/terraform:1.6.6
            entrypoint: [""]

.assume role:
    assume_role_token: &assume_role_token
        id_tokens:
            GITLAB_OIDC_TOKEN:
                  aud: https://gitlab.revolve.team
    script: &assume_role_script
        - apk add --no-cache aws-cli
        - >
            export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
            $(aws sts assume-role-with-web-identity
            --role-arn ${ROLE_ARN}
            --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
            --web-identity-token ${GITLAB_OIDC_TOKEN}
            --duration-seconds 3600
            --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
            --output text))
        - aws sts get-caller-identity



terraform_plan:
    <<: *image_terraform
    <<: *assume_role_token
    stage: plan
    rules:
        - if: $CI_COMMIT_BRANCH == "gitlab-ci" && $CI_PIPELINE_SOURCE == "push"
    script:
        - *assume_role_script
        - terraform init
        - terraform plan -out=${TERRAFORM_PLAN_FILE} -var-file="variables.tfvars"
    artifacts:
        paths:
            - $TERRAFORM_PLAN_FILE
            - .terraform.lock.hcl
            

terraform_apply:
    <<: *image_terraform
    <<: *assume_role_token
    stage: apply
    rules:
        - if: $CI_COMMIT_BRANCH == "gitlab-ci" && $CI_PIPELINE_SOURCE == "push"
          when: manual
    script:
        - *assume_role_script
        - terraform init
        - terraform apply ${TERRAFORM_PLAN_FILE}

terraform_destroy:
    <<: *image_terraform
    <<: *assume_role_token
    stage: apply
    rules:
        - if: $CI_COMMIT_BRANCH == "gitlab-ci" && $CI_PIPELINE_SOURCE == "push"
          when: manual
    script:
        - *assume_role_script
        - terraform init
        - terraform destroy -auto-approve -var-file="variables.tfvars"

