assume_role:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.revolve.team
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.13.32.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - echo $GITLAB_OIDC_TOKEN
    - echo $id_tokens
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - echo "plan terrafomr"
    - make plan
