assume_role:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.revolve.team
  script:
    - sudo apt install awscli -y
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity


variables:
  # Vous pouvez définir des variables personnalisées ici

# Définition du workflow
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
      - echo "Étape de test en cours..."
      - make plan
  needs:
   - assume_role


# # Définition du workflow
# workflow:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "push"'
#     - if: '$CI_COMMIT_BRANCH == "main"'
#   script:
#       - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#       - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#       - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
#       - echo "Étape de test en cours..."
#       - make plan
